version: "3.8"
services:
    postgres:
        image: "postgres:14"
        restart: always
        env_file:
            - .env.api.prod
        volumes:
            - ./database:/var/lib/postgresql/data
            - ./ddl:/ddl
        networks:
            - backend
    api:
        build:
            context: ./api
        volumes:
            - ./api/app:/api/app
        ports:
            - "4000:4000"
        depends_on:
            - "postgres"
        env_file:
            - .env.api.prod
        restart: always
        networks:
            - web
            - backend
    websocket-server:
        build:
            context: ./websocket-server
        volumes:
            - ./websocket-server/app:/websocket-server/app

        env_file:
            - .env.api.prod
        ports:
            - "7000:7000"
        restart: always
        networks:
            - web
    react-app:
        image: "tomekq13/easy-estimator-react:latest"
        container_name: react-app
        restart: always
        expose:
            - "80"
        env_file:
            - react-app.env
        networks:
            - web
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./nginx/ssl:/etc/letsencrypt
            - ./nginx/certbot:/var/www/certbot
        entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 6h & wait $${!}; done;"
        networks:
            - web
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/ssl:/etc/nginx/ssl
            - ./nginx/certbot:/var/www/certbot # this is to handle the challenge on refresh, this you give as a path to the certbot renew
        depends_on:
            - react-app
            - api
            - websocket-server
        networks:
            - web
        restart: always
networks:
    web:
        driver: bridge
    backend:
        driver: bridge
