version: '3'
services:
  postgres:
    image: 'postgres:14'
    restart: always
    env_file:
      - .env.api.dev
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./ddl:/ddl
  api:
    build:
      context: ./api
    volumes:
      - ./api:/api
    ports:
      - '4000:4000'
    depends_on:
      - 'postgres'
    env_file:
      - .env.api.prod
    restart: always
  websocket-server:
    build:
      context: ./websocket-server
    volumes:
      - ./websocket-server:/websocket-server
    ports:
      - '7000:7000'
    restart: always
  react-app:
    image: 'tomekq13/easy-estimator-react'
    restart: always
    ports:
      - '80:80'
    env_file:
      - react-app.env